- name: "Run all role tasks"
  block:
    - name: "Create ZFS Datasets utility script"
      ansible.builtin.include_tasks: create_util_script/main.yml
    - name: "Configure ZFS datasets"
      ansible.builtin.include_tasks: config_datasets/main.yml
    - name: "Configure querying user for encrypted-dataset passphrases at boot"
      ansible.builtin.include_tasks: config_decrypt/main.yml
  always:
    - name: "Run all cleanup tasks"
      ansible.builtin.include_tasks: cleanup/main.yml

