- name: "Create zfs filesystem-dataset '{{ dataset_name }}'{{ mountpoint_name }}"
  community.general.zfs:
    name: "{{ dataset_name }}"
    state: present
    extra_zfs_properties:
      mountpoint: "{{ (mount_point == 'inherited') | ternary(omit, mount_point) }}"
  vars:
    dataset_name: "{{ pool }}/{{ dataset_path }}"
    mountpoint_descrip: " on mountpoint '{{ mount_point }}'"
    mountpoint_name: "{{ '' if (mount_point == 'inherited') else mountpoint_descrip }}"

