- name: "Create a zfs filesystem dataset, and set filesystem attributes on it"
  ansible.builtin.include_tasks: create_dataset.yml
  vars:
    dataset_name: "{{ dataset.pool }}{{ dataset.path }}"
    mountpoint_descrip: " on mountpoint '{{ dataset.mount }}'"
    mountpoint_name: "{{ '' if (dataset.mount == 'inherited') else mountpoint_descrip }}"
  loop: "{{ filesystem_datasets }}"
  loop_control:
    loop_var: dataset

