- name: "Create custom decrypt-zfs-datasets-at-boot RC service at '{{ zfs_datasets_freebsd_rc_d_script_filepath }}'"
  ansible.builtin.template:
    dest: "{{ zfs_datasets_freebsd_rc_d_script_filepath }}"
    src: "zfs_datasets_decrypt_at_boot_sh.j2"
    force: true
    mode: '0755'
  become: true
  become_user: root

- name: "Enable custom decrypt-zfs-datasets-at-boot RC service in '{{ zfs_datasets_freebsd_rc_conf_filepath }}'"
  community.general.sysrc:
    path: "{{ zfs_datasets_freebsd_rc_conf_filepath }}"
    name: "zfs_datasets_decrypt_at_boot_enable"
    value: "YES"
    state: present
  become: true
  become_user: root

