- name: "Add persistent dataset properties"
  ansible.builtin.set_fact:
    zfs_dataset_persist_props: "{{ zfs_dataset_persist_props | combine({ prop.prop_nm: prop.prop_val }) }}"
  loop:
    - { prop_nm: "keyformat", prop_val: "passphrase", add: "{{ zfs_dataset_enc_enable }}" }
    - { prop_nm: "keylocation", prop_val: "prompt", add: "{{ zfs_dataset_enc_enable }}" }
    - { prop_nm: "sharenfs", prop_val: "{{ 'on' if zfs_dataset_nfs_enable else 'off' }}", add: true }
  loop_control:
    loop_var: prop
  when: prop.add

