- name: "Check status of pool '{{ dataset_pool }}'"
  ansible.builtin.command:
    cmd: "zpool list {{ dataset_pool }}"
  register: pool_exists_result
  changed_when: false
  failed_when: false

- name: "Assert that pool '{{ dataset_pool }}' exists on the system"
  ansible.builtin.assert:
    that: "pool_exists_result.rc == 0"
    fail_msg: "You must create or import pool '{{ dataset_pool }}' prior to creating datasets"
    quiet: true

- name: "Get mountpoint of pool '{{ dataset_pool }}'"
  ansible.builtin.command:
    cmd: "zfs get -H -o value -p mountpoint {{ dataset_pool }}"
  register: pool_mountpoint_result
  changed_when: false

- name: "Assert that pool mountpoint '{{ mountpoint }}' is in base path of dataset path '{{ dataset.path }}'"
  ansible.builtin.assert:
    that: "dataset.path.startswith(mountpoint)"
    fail_msg: "dataset should be on pool '{{ dataset_pool }}', which has mountpoint '{{ mountpoint }}"
    quiet: true
  vars:
    mountpoint: "{{ pool_mountpoint_result.stdout }}"

- name: "Check if filesystem-dataset '{{ dataset_name }}' exists"
  ansible.builtin.command:
    cmd: "zfs list {{ dataset_name }}"
  register: dataset_exists_result
  changed_when: dataset_exists_result.rc == 1
  failed_when: dataset_exists_result.rc > 1

