# the zfs filesystem-datasets to create, along with the owner/group/permissions
# --> pool: the zpool to create the dataset on
# --> stem: partial sub-path, starting with "/", to append after pool name
#           dataset will be mounted at [pool-mountpoint][stem]
#           dataset will inherit properties of parent datasets in stem's path
# --> owner: user that owns the dataset
# --> group: group that owns the dataset
# --> mode: file mode of the dataset
# --> enc: encryption passphrase for dataset (empty str for no encryption)
zfs_datasets_to_create: []
# - { pool: 'zroot', stem: '/home',             owner: 'root',  group: 'wheel', mode: '755', enc: '' }
# - { pool: 'zroot', stem: '/home/user2',       owner: 'user2', group: 'user2', mode: '710', enc: '' }
# - { pool: 'zroot', stem: '/home/user2/Trash', owner: 'user2', group: 'user2', mode: '755', enc: '' }

# on boot, query user for any passphrases required to mount zfs datasets
zfs_datasets_decrypt_at_boot: true

# on creation of an encrypted dataset, temporarily store the password in a file
zfs_datasets_temp_enc_pswd_path: "/tmp/ans_role_config_zfs_datasets_enc_pswd.txt"

